version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
      - PORT=3000
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FRONTEND_URL=http://localhost:3000
      - PLAYER_SERVICE_URL=http://player-service:5001
    depends_on:
      - player-service
    networks:
      - app-network

  player-service:
    build: ./player-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://localhost:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 