[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8080
min_machines_running = 0
processes = [ "app" ]

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 8080  # External/public port