# fly.toml app configuration file generated for k-pong-backend on 2025-05-13T18:55:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'k-pong-backend'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.ports]]
  port = 8080
  handlers = ["http", "tls", "ws"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
