# fly.toml app configuration file generated for k-pong-backend on 2025-05-13T18:55:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "k-pong-backend"
primary_region = "arn"

[env]
  PORT = "8080"
  NODE_ENV = "production"
  FRONTEND_URL = "https://k-pong.fly.dev"
  PLAYER_SERVICE_URL = "http://k-pong-player-service.internal:5001"

[build]
  [build.args]
    NODE_VERSION = "18"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    hard_limit = 1000
    soft_limit = 1000
    type = "connections"

  [[http_service.ports]]
    handlers = ["http", "tls", "ws"]
    port = 8080

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
