# fly.toml app configuration file generated for k-pong-mongodb on 2025-05-14T22:41:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'k-pong-mongodb'
primary_region = 'arn'

[build]

[[mounts]]
  source = 'db'
  destination = '/data/db'

[[services]]
  protocol = "tcp"
  internal_port = 27017
  processes = ["app"]
  
  [[services.ports]]
    port = 27017
    handlers = ["tcp"]
  
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
