# fly.toml app configuration file generated for k-pong-mongodb on 2025-05-14T22:41:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'k-pong-mongodb'
primary_region = 'arn'

[build]

[mounts]
  source = 'mongodb_data'
  destination = '/data/db'

[env]
  MONGO_INITDB_ROOT_USERNAME = ""
  MONGO_INITDB_ROOT_PASSWORD = ""

# Use a simple TCP service without handlers
[[services]]
  internal_port = 27017
  protocol = "tcp"

  [[services.ports]]
    port = 27017

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
