app = 'k-pong-mongodb'
primary_region = 'arn'

[build]

[mounts]
  source = 'mongodb_data'  # Changed back to 'mongodb_data' to match existing volume
  destination = '/data/db'

[env]
  MONGO_INITDB_ROOT_USERNAME = ""
  MONGO_INITDB_ROOT_PASSWORD = ""

# Use a simple TCP service without handlers
[[services]]
  internal_port = 27017
  protocol = "tcp"

  [[services.ports]]
    port = 27017

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1